# Generated by Django 4.1.6 on 2023-05-05 22:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fo', '0009_flightoperator_class_list'),
        ('simapp', '0040_alter_mission_final_pitch_alter_mission_final_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='final_pitch',
            field=models.IntegerField(blank=True, default=-74, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='mission',
            name='final_roll',
            field=models.IntegerField(blank=True, default=163, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='mission',
            name='final_yaw',
            field=models.IntegerField(blank=True, default=141, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.RemoveField(
            model_name='sim',
            name='ACS_fo',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='COMMS_fo',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='EPS_fo',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='TCS_fo',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='flight_director',
        ),
        migrations.AddField(
            model_name='sim',
            name='ACS_fo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='acs_fo', to='fo.flightoperator', verbose_name='ACS Flight Operator'),
        ),
        migrations.AddField(
            model_name='sim',
            name='COMMS_fo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='comms_fo', to='fo.flightoperator', verbose_name='Comms Flight Operator'),
        ),
        migrations.AddField(
            model_name='sim',
            name='EPS_fo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='eps_fo', to='fo.flightoperator', verbose_name='EPS Flight Operator'),
        ),
        migrations.AddField(
            model_name='sim',
            name='TCS_fo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tcs_fo', to='fo.flightoperator', verbose_name='TCS Flight Operator'),
        ),
        migrations.AddField(
            model_name='sim',
            name='flight_director',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='flight_director', to='fo.flightoperator', verbose_name='Flight Director (Payload Flight Operator)'),
        ),
    ]
